Enabling refreshing zone on keysize change
codysnider/coredns-redis pull request #2
Opened 2024-08-17 06:20 UTC by ajeygore

If we add a zone dynamically - that might be required in some cases, when you are dealing with multiple sub domain, this lookup redis for keysize and then reloads all the zone.

2025-04-11 23:07 UTC, codysnider commented on redis.go
> +	fmt.Println("loading zones")
let's use the logger

2025-04-11 23:07 UTC, codysnider commented on redis.go
> +		fmt.Println("error parsing dbsize:", err)
let's use the logger

2025-04-11 23:07 UTC, codysnider commented on redis.go
> +		fmt.Println("error getting dbsize from redis:", err)
let's use the logger

2025-04-11 23:07 UTC, codysnider commented on redis.go
> +	defer conn.Close()
I don't think we want the connection closed.

2025-04-11 23:07 UTC, codysnider commented on redis.go
> +		fmt.Println("error connecting to redis")
let's use the logger

2025-04-11 23:08 UTC, codysnider requested changes
couple minor changes

2025-06-30 19:39 UTC, closed without merging

2025-07-17 15:47 UTC, ajeygore commented
I have opened a fresh pull request - incorporating all changes requested.

Here is the new pull request with upstream merge. https://github.com/codysnider/coredns-redis/pull/8